# Generated by Django 5.2.8 on 2025-11-21 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('immigration', 'Immigration'), ('healthcare', 'Healthcare'), ('gun_rights', 'Gun Rights'), ('abortion', 'Abortion'), ('climate', 'Climate Change'), ('economy', 'Economy & Trade'), ('education', 'Education'), ('criminal_justice', 'Criminal Justice'), ('foreign_policy', 'Foreign Policy'), ('taxation', 'Taxation')], max_length=50)),
                ('subcategory', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('stance', models.CharField(max_length=100)),
                ('hypothesis', models.CharField(max_length=250)),
                ('conclusion', models.CharField(max_length=250)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pro', 'Pro'), ('con', 'Con')], max_length=3)),
                ('summary', models.CharField(max_length=150)),
                ('detail', models.TextField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='core.card')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.argument')),
            ],
        ),
    ]
