# Generated by Django 5.2.8 on 2025-12-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default='private', max_length=10),
        ),
    ]
