# Generated by Django 5.2.8 on 2025-12-05 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_directmessage_usersettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='argument',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='argument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 5, 4, 12, 55, 970746, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='scope',
            field=models.CharField(choices=[('federal', 'Federal'), ('state', 'State')], default='federal', max_length=20),
        ),
        migrations.AddField(
            model_name='source',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='source',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='source',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='argument',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='argument',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='conclusion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='hypothesis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='subcategory',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='card',
            name='topic',
            field=models.CharField(choices=[('immigration_policy', 'Immigration Policy'), ('healthcare_reform', 'Healthcare Reform'), ('gun_control', 'Gun Control'), ('abortion_rights', 'Abortion Rights'), ('climate_change_policy', 'Climate Change Policy'), ('tax_policy', 'Tax Policy'), ('social_security', 'Social Security'), ('medicare_medicaid', 'Medicare/Medicaid'), ('foreign_policy', 'Foreign Policy'), ('military_spending', 'Military Spending'), ('education_funding', 'Education Funding'), ('infrastructure', 'Infrastructure'), ('criminal_justice_reform', 'Criminal Justice Reform'), ('drug_policy', 'Drug Policy'), ('labor_laws', 'Labor Laws'), ('minimum_wage', 'Minimum Wage'), ('trade_policy', 'Trade Policy'), ('national_security', 'National Security'), ('voting_rights', 'Voting Rights'), ('campaign_finance', 'Campaign Finance'), ('state_income_tax', 'State Income Tax'), ('property_tax', 'Property Tax'), ('state_education_funding', 'State Education Funding'), ('marijuana_legalization', 'Marijuana Legalization'), ('death_penalty', 'Death Penalty'), ('state_healthcare', 'State Healthcare'), ('gun_regulations', 'Gun Regulations'), ('abortion_access', 'Abortion Access'), ('voting_laws', 'Voting Laws'), ('police_reform', 'Police Reform'), ('prison_reform', 'Prison Reform'), ('environmental_regulations', 'Environmental Regulations'), ('state_minimum_wage', 'State Minimum Wage'), ('workers_rights', 'Workers Rights'), ('housing_policy', 'Housing Policy'), ('transportation', 'Transportation'), ('public_safety', 'Public Safety'), ('zoning_laws', 'Zoning Laws'), ('state_budgets', 'State Budgets'), ('redistricting', 'Redistricting')], max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
