# Generated by Django 5.2.8 on 2025-12-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_argument_options_alter_card_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcard',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
