# Generated by Django 5.2.8 on 2025-12-08 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_savedcard_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='cards.card'),
        ),
    ]
