# Generated by Django 5.2.8 on 2025-12-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_make_conversation_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
