# Generated by Django 5.2.8 on 2025-12-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_cardversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='home_state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
