# Generated by Django 5.2.8 on 2025-12-09 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_usersettings_bio_usersettings_birthdate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('youtube', 'YouTube Video'), ('article', 'Article/Link'), ('note', 'Text Note'), ('quote', 'Quote')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('description', models.TextField(blank=True, max_length=500)),
                ('topic', models.CharField(choices=[('immigration_policy', 'Immigration Policy'), ('healthcare_reform', 'Healthcare Reform'), ('gun_control', 'Gun Control'), ('abortion_rights', 'Abortion Rights'), ('climate_change_policy', 'Climate Change Policy'), ('tax_policy', 'Tax Policy'), ('social_security', 'Social Security'), ('medicare_medicaid', 'Medicare/Medicaid'), ('foreign_policy', 'Foreign Policy'), ('military_spending', 'Military Spending'), ('education_funding', 'Education Funding'), ('infrastructure', 'Infrastructure'), ('criminal_justice_reform', 'Criminal Justice Reform'), ('drug_policy', 'Drug Policy'), ('labor_laws', 'Labor Laws'), ('minimum_wage', 'Minimum Wage'), ('trade_policy', 'Trade Policy'), ('national_security', 'National Security'), ('voting_rights', 'Voting Rights'), ('campaign_finance', 'Campaign Finance'), ('state_income_tax', 'State Income Tax'), ('property_tax', 'Property Tax'), ('state_education_funding', 'State Education Funding'), ('marijuana_legalization', 'Marijuana Legalization'), ('death_penalty', 'Death Penalty'), ('state_healthcare', 'State Healthcare'), ('gun_regulations', 'Gun Regulations'), ('abortion_access', 'Abortion Access'), ('voting_laws', 'Voting Laws'), ('police_reform', 'Police Reform'), ('prison_reform', 'Prison Reform'), ('environmental_regulations', 'Environmental Regulations'), ('state_minimum_wage', 'State Minimum Wage'), ('workers_rights', 'Workers Rights'), ('housing_policy', 'Housing Policy'), ('transportation', 'Transportation'), ('public_safety', 'Public Safety'), ('zoning_laws', 'Zoning Laws'), ('state_budgets', 'State Budgets'), ('redistricting', 'Redistricting')], max_length=100)),
                ('stance', models.CharField(choices=[('supporting', 'Supporting'), ('opposing', 'Opposing'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notebook entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
