# Generated by Django 5.2.8 on 2025-12-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_alter_usersettings_home_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='topic',
            field=models.CharField(choices=[('general', 'General Research'), ('immigration_policy', 'Immigration Policy'), ('healthcare_reform', 'Healthcare Reform'), ('gun_control', 'Gun Control'), ('abortion_rights', 'Abortion Rights'), ('climate_change_policy', 'Climate Change Policy'), ('tax_policy', 'Tax Policy'), ('social_security', 'Social Security'), ('medicare_medicaid', 'Medicare/Medicaid'), ('foreign_policy', 'Foreign Policy'), ('military_spending', 'Military Spending'), ('education_funding', 'Education Funding'), ('infrastructure', 'Infrastructure'), ('criminal_justice_reform', 'Criminal Justice Reform'), ('drug_policy', 'Drug Policy'), ('labor_laws', 'Labor Laws'), ('minimum_wage', 'Minimum Wage'), ('trade_policy', 'Trade Policy'), ('national_security', 'National Security'), ('voting_rights', 'Voting Rights'), ('campaign_finance', 'Campaign Finance'), ('state_income_tax', 'State Income Tax'), ('property_tax', 'Property Tax'), ('state_education_funding', 'State Education Funding'), ('marijuana_legalization', 'Marijuana Legalization'), ('death_penalty', 'Death Penalty'), ('state_healthcare', 'State Healthcare'), ('gun_regulations', 'Gun Regulations'), ('abortion_access', 'Abortion Access'), ('voting_laws', 'Voting Laws'), ('police_reform', 'Police Reform'), ('prison_reform', 'Prison Reform'), ('environmental_regulations', 'Environmental Regulations'), ('state_minimum_wage', 'State Minimum Wage'), ('workers_rights', 'Workers Rights'), ('housing_policy', 'Housing Policy'), ('transportation', 'Transportation'), ('public_safety', 'Public Safety'), ('zoning_laws', 'Zoning Laws'), ('state_budgets', 'State Budgets'), ('redistricting', 'Redistricting')], max_length=100),
        ),
        migrations.AlterField(
            model_name='notebookentry',
            name='topic',
            field=models.CharField(choices=[('general', 'General Research'), ('immigration_policy', 'Immigration Policy'), ('healthcare_reform', 'Healthcare Reform'), ('gun_control', 'Gun Control'), ('abortion_rights', 'Abortion Rights'), ('climate_change_policy', 'Climate Change Policy'), ('tax_policy', 'Tax Policy'), ('social_security', 'Social Security'), ('medicare_medicaid', 'Medicare/Medicaid'), ('foreign_policy', 'Foreign Policy'), ('military_spending', 'Military Spending'), ('education_funding', 'Education Funding'), ('infrastructure', 'Infrastructure'), ('criminal_justice_reform', 'Criminal Justice Reform'), ('drug_policy', 'Drug Policy'), ('labor_laws', 'Labor Laws'), ('minimum_wage', 'Minimum Wage'), ('trade_policy', 'Trade Policy'), ('national_security', 'National Security'), ('voting_rights', 'Voting Rights'), ('campaign_finance', 'Campaign Finance'), ('state_income_tax', 'State Income Tax'), ('property_tax', 'Property Tax'), ('state_education_funding', 'State Education Funding'), ('marijuana_legalization', 'Marijuana Legalization'), ('death_penalty', 'Death Penalty'), ('state_healthcare', 'State Healthcare'), ('gun_regulations', 'Gun Regulations'), ('abortion_access', 'Abortion Access'), ('voting_laws', 'Voting Laws'), ('police_reform', 'Police Reform'), ('prison_reform', 'Prison Reform'), ('environmental_regulations', 'Environmental Regulations'), ('state_minimum_wage', 'State Minimum Wage'), ('workers_rights', 'Workers Rights'), ('housing_policy', 'Housing Policy'), ('transportation', 'Transportation'), ('public_safety', 'Public Safety'), ('zoning_laws', 'Zoning Laws'), ('state_budgets', 'State Budgets'), ('redistricting', 'Redistricting')], max_length=100),
        ),
    ]
