# Generated by Django 5.2.8 on 2025-12-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_alter_card_topic_alter_notebookentry_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookentry',
            name='topic',
            field=models.CharField(choices=[('general', 'General Research'), ('politics', 'Politics & Government'), ('healthcare', 'Healthcare & Medicine'), ('economy', 'Economy & Business'), ('education', 'Education'), ('environment', 'Environment & Climate'), ('technology', 'Technology & Science'), ('social', 'Social Issues'), ('international', 'International Affairs'), ('legal', 'Legal & Justice'), ('culture', 'Culture & Society'), ('other', 'Other')], max_length=100),
        ),
    ]
