# Generated by Django 5.2.8 on 2025-12-10 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0020_alter_notebookentry_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cards.notebookentry')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
