# Generated by Django 5.2.8 on 2025-12-10 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_notebooknote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcard',
            name='original_source',
            field=models.CharField(blank=True, help_text='Name of public figure or source', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='savedcard',
            name='source_type',
            field=models.CharField(choices=[('user', 'User Created'), ('commons', 'Debrief Commons'), ('public_figure', 'Public Figure (Unverified)'), ('verified', 'Verified Public Figure')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='savedcard',
            name='source_url',
            field=models.URLField(blank=True, help_text='Link to original content', null=True),
        ),
        migrations.AddField(
            model_name='savedcard',
            name='synthesized_by',
            field=models.ForeignKey(blank=True, help_text='User who created this synthesis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synthesized_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
