# Generated by Django 5.2.8 on 2025-12-10 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0022_savedcard_original_source_savedcard_source_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('maps_to', models.CharField(choices=[('stance', 'Stance (For/Against)'), ('hypothesis', 'Hypothesis'), ('supporting', 'Supporting Argument'), ('opposing', 'Opposing Argument'), ('conclusion', 'Conclusion'), ('scope', 'Scope (Federal/State)')], max_length=20)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TopicSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('general', 'General Research'), ('immigration_policy', 'Immigration Policy'), ('healthcare_reform', 'Healthcare Reform'), ('gun_control', 'Gun Control'), ('abortion_rights', 'Abortion Rights'), ('climate_change_policy', 'Climate Change Policy'), ('tax_policy', 'Tax Policy'), ('social_security', 'Social Security'), ('medicare_medicaid', 'Medicare/Medicaid'), ('foreign_policy', 'Foreign Policy'), ('military_spending', 'Military Spending'), ('education_funding', 'Education Funding'), ('infrastructure', 'Infrastructure'), ('criminal_justice_reform', 'Criminal Justice Reform'), ('drug_policy', 'Drug Policy'), ('labor_laws', 'Labor Laws'), ('minimum_wage', 'Minimum Wage'), ('trade_policy', 'Trade Policy'), ('national_security', 'National Security'), ('voting_rights', 'Voting Rights'), ('campaign_finance', 'Campaign Finance'), ('state_income_tax', 'State Income Tax'), ('property_tax', 'Property Tax'), ('state_education_funding', 'State Education Funding'), ('marijuana_legalization', 'Marijuana Legalization'), ('death_penalty', 'Death Penalty'), ('state_healthcare', 'State Healthcare'), ('gun_regulations', 'Gun Regulations'), ('abortion_access', 'Abortion Access'), ('voting_laws', 'Voting Laws'), ('police_reform', 'Police Reform'), ('prison_reform', 'Prison Reform'), ('environmental_regulations', 'Environmental Regulations'), ('state_minimum_wage', 'State Minimum Wage'), ('workers_rights', 'Workers Rights'), ('housing_policy', 'Housing Policy'), ('transportation', 'Transportation'), ('public_safety', 'Public Safety'), ('zoning_laws', 'Zoning Laws'), ('state_budgets', 'State Budgets'), ('redistricting', 'Redistricting')], max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Context or stats about this topic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('card_value', models.TextField(help_text='Text that will be used in the argument card')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='cards.surveyquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cards.topicsurvey'),
        ),
    ]
