# Generated by Django 5.2.8 on 2025-12-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0024_add_question_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_url', models.URLField()),
                ('api_endpoint', models.URLField(blank=True, help_text='API endpoint if available')),
                ('api_key_required', models.BooleanField(default=False)),
                ('credibility_rating', models.IntegerField(default=80, help_text='1-100')),
                ('source_type', models.CharField(choices=[('government', 'Government Agency'), ('academic', 'Academic Institution'), ('think_tank', 'Think Tank'), ('news', 'News Organization'), ('ngo', 'Non-Profit Organization')], max_length=50)),
                ('topics', models.JSONField(default=list, help_text='List of topics this source covers')),
            ],
            options={
                'ordering': ['-credibility_rating'],
            },
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='context_stats',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='learn_more',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='sources',
        ),
        migrations.CreateModel(
            name='PolicyFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('general', 'General Research'), ('immigration_policy', 'Immigration Policy'), ('healthcare_reform', 'Healthcare Reform'), ('gun_control', 'Gun Control'), ('abortion_rights', 'Abortion Rights'), ('climate_change_policy', 'Climate Change Policy'), ('tax_policy', 'Tax Policy'), ('social_security', 'Social Security'), ('medicare_medicaid', 'Medicare/Medicaid'), ('foreign_policy', 'Foreign Policy'), ('military_spending', 'Military Spending'), ('education_funding', 'Education Funding'), ('infrastructure', 'Infrastructure'), ('criminal_justice_reform', 'Criminal Justice Reform'), ('drug_policy', 'Drug Policy'), ('labor_laws', 'Labor Laws'), ('minimum_wage', 'Minimum Wage'), ('trade_policy', 'Trade Policy'), ('national_security', 'National Security'), ('voting_rights', 'Voting Rights'), ('campaign_finance', 'Campaign Finance'), ('state_income_tax', 'State Income Tax'), ('property_tax', 'Property Tax'), ('state_education_funding', 'State Education Funding'), ('marijuana_legalization', 'Marijuana Legalization'), ('death_penalty', 'Death Penalty'), ('state_healthcare', 'State Healthcare'), ('gun_regulations', 'Gun Regulations'), ('abortion_access', 'Abortion Access'), ('voting_laws', 'Voting Laws'), ('police_reform', 'Police Reform'), ('prison_reform', 'Prison Reform'), ('environmental_regulations', 'Environmental Regulations'), ('state_minimum_wage', 'State Minimum Wage'), ('workers_rights', 'Workers Rights'), ('housing_policy', 'Housing Policy'), ('transportation', 'Transportation'), ('public_safety', 'Public Safety'), ('zoning_laws', 'Zoning Laws'), ('state_budgets', 'State Budgets'), ('redistricting', 'Redistricting')], max_length=50)),
                ('fact_text', models.TextField(help_text='The factual statement')),
                ('source_name', models.CharField(help_text='Source organization', max_length=200)),
                ('source_url', models.URLField()),
                ('date_published', models.DateField(blank=True, null=True)),
                ('last_verified', models.DateTimeField(auto_now=True)),
                ('fact_type', models.CharField(choices=[('statistic', 'Statistic'), ('study', 'Academic Study'), ('poll', 'Public Opinion Poll'), ('law', 'Legal/Policy Info'), ('comparison', 'International Comparison')], max_length=50)),
                ('relevance_score', models.IntegerField(default=50, help_text='1-100, how relevant/important')),
            ],
            options={
                'ordering': ['-relevance_score', '-last_verified'],
                'indexes': [models.Index(fields=['topic', '-relevance_score'], name='cards_polic_topic_11773a_idx')],
            },
        ),
    ]
