# Generated by Django 5.2.8 on 2025-12-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0026_add_question_context_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebooknote',
            name='timestamp',
            field=models.CharField(blank=True, help_text='Video timestamp HH:MM:SS', max_length=10),
        ),
    ]
