# Generated by Django 5.2.8 on 2025-12-11 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0027_notebooknote_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Why you are sharing this', max_length=500)),
                ('notebook_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.notebookentry')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_digests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shared_at'],
                'unique_together': {('shared_by', 'notebook_entry')},
            },
        ),
        migrations.CreateModel(
            name='SquadDigestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('timestamp', models.CharField(blank=True, help_text='Video timestamp HH:MM:SS', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_notes', to='cards.squaddigest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
